name: gradle

'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: set up environment
        run: echo ::set-env name=ARTIFACT_NAME::"$GITHUB_SHA"

      - name: checkout changes
        uses: actions/checkout@v2

      - name: prepare java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: prepare depdendency cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: '${{ runner.os }}-gradle-${{ hashFiles(''**/*.gradle'') }}'
          restore-keys: '${{ runner.os }}-gradle'

      - name: prepare gradlew fileperms
        run: chmod +x gradlew

      - name: run gradle build
        run: ./gradlew build

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: '${{ env.ARTIFACT_NAME }}'
          path: build/libs/*.jar
