name: release

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: checkout changes
        uses: actions/checkout@v2

      - name: get timestamp
        run: echo ::set-env name=EPOCH::"$(date +%s)"

      - name: prepare release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.EPOCH }}
          release_name: ${{ env.EPOCH }}
          body: automated release at epoch ${{ env.EPOCH }}
          draft: false
          prerelease: false

      - name: prepare java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: prepare depdendency cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: '${{ runner.os }}-gradle-${{ hashFiles(''**/*.gradle'') }}'
          restore-keys: '${{ runner.os }}-gradle'

      - name: prepare gradlew fileperms
        run: chmod +x gradlew

      - name: run gradle build
        run: ./gradlew build

      - name: upload release assets
        uses: csexton/release-asset-action@v2
        with:
          pattern: "build/libs/*.jar"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
