version: 2
updates:

- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
    time: "12:00"
    timezone: "Europe/Berlin"
  assignees:
    - "nothub"
  reviewers:
    - "nothub"
  commit-message:
    prefix: "docker"
    include: "scope"
