version: 2
updates:

- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
    time: "12:00"
    timezone: "Europe/Berlin"
  assignees:
    - "blockparole"
  reviewers:
    - "blockparole"
  commit-message:
    prefix: "gomod"
    include: "scope"

- package-ecosystem: "gitsubmodule"
  directory: "/"
  schedule:
    interval: "daily"
    time: "12:00"
    timezone: "Europe/Berlin"
  assignees:
    - "blockparole"
  reviewers:
    - "blockparole"
  commit-message:
    prefix: "gitsubmodule"
    include: "scope"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "12:00"
    timezone: "Europe/Berlin"
  assignees:
    - "blockparole"
  reviewers:
    - "blockparole"
  commit-message:
    prefix: "github-actions"
    include: "scope"

- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
    time: "12:00"
    timezone: "Europe/Berlin"
  assignees:
    - "blockparole"
  reviewers:
    - "blockparole"
  commit-message:
    prefix: "docker"
    include: "scope"
