name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: checkout changes
        uses: actions/checkout@v2

      - name: get timestamp
        run: echo ::set-env name=EPOCH::"$(date +%s)"

      - name: prepare release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.EPOCH }}
          release_name: ${{ env.EPOCH }}
          body: automated release at epoch ${{ env.EPOCH }}
          draft: false
          prerelease: false

      - name: prepare python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: run
        run: python run.py

      - name: upload release assets
        uses: csexton/release-asset-action@v2
        with:
          file: asset.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}

